name: 'Setup mkr'
description: 'Setup mkr - CLI for Mackerel'
author: 'Susisu <susisu2413@yahoo.co.jp>'
branding:
  icon: activity
  color: white
inputs:
  mkr-version:
    description: 'The version of mkr to use.'
  token:
    description: 'The GitHub token used to get mkr versions'
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
